### ISSUE TITLE
Where are the tags filed in the VM type?

### ISSUE THREAD

**Issue by moadqassem** [anexia-it/go-anxcloud#1]
Looking at the VM type, I saw that you have a field which is called Tags https://github.com/anexia-it/go-anxcloud/blob/main/pkg/vsphere/search/name.go#L28, how someone can actually set that field using the api?

**Comment by erdii** [comment]
@moadqassem this is currently WIP and part of the `core` API at anexia: https://engine.anexia-it.com/api/core/doc/#!/tags
Basically every object in their API can be tagged using a bunch of separate tagging endpoints.

**Comment by paepke** [comment]
The tag endpoint is implemented - closing this ticket
