### ISSUE TITLE
The field 'custom_name' is missing in the api client  

### ISSUE THREAD

**Issue by moadqassem** [anexia-it/go-anxcloud#2]
Looking at what the api returns when sending a get request to this endpoint here `/api/vsphere/v1/info.json/[vm-id]/info`, I noticed that, there is a field called `custom_name`, however, I don't see that field in the Definition type, which means it is not possible to set it not get it. This field is quite important to add some essential meta data about the machine, especially that, the hostname will be prefixed with another value.

**Comment by eqrx** [comment]
Hi, please take a look at https://github.com/anexia-it/go-anxcloud/blob/e70d2450d0413f705f9de46be12fdd15dc5cc333/pkg/vsphere/info/info.go#L19

Is that not the field you want? You can perform a get via the info package. I am not aware of a way how to set it via the API

**Comment by moadqassem** [comment]
That's the thing, I took a look on this type before adding the ticket and as an API user only this field is kinda useless if I can't set it :)

**Comment by paepke** [comment]
The attribute will be there in an upcomming api release - thanks for the hint.
